kind: pipeline
name: default

steps:
  - name: deploy_droplet
    image: curlimages/curl:latest
    environment:
      DO_TOKEN:
        from_secret: do_token  # Use the secret for the token
    commands:
      - |
        curl -X POST "https://api.digitalocean.com/v2/droplets" \
          -d '{"name":"My-Droplet","region":"nyc3","size":"s-1vcpu-1gb","image":"ubuntu-20-04-x64"}' \
          -H "Authorization: Bearer dop_v1_ce737b415e549abbc98d8b49eb416d73ad7cfab804a34913d7e35e0767c6ee4d" \
          -H "Content-Type: application/json"

trigger:
  event:
    - push
  branch:
    - main
