kind: pipeline
name: default

steps:
  - name: install_dependencies
    image: python:3.8
    commands:
      - pip install requests
      - pip install simplejson

  - name: deploy_droplet
    image: curlimages/curl
    commands:
      - |
        curl --request POST \
          --url https://api.linode.com/v4/linode/instances \
          --header 'accept: application/json' \
          --header 'authorization: Bearer $LINODE_API_KEY' \
          --header 'content-type: application/json' \
          --data '{
            "booted": true,
            "interfaces": [
              {
                "primary": true,
                "purpose": "public"
              }
            ],
            "swap_size": 512
          }'

trigger:
  event:
    - push
    - pull_request
  branch:
    - main
