kind: pipeline
name: default

steps:
  - name: deploy_droplet
    image: curlimages/curl:latest
    environment:
      DO_TOKEN:
        from_secret: do_token  # Use the secret for the token
    commands:
      - |
        curl -X POST "https://api.digitalocean.com/v2/droplets" \
          -d '{"name":"My-Droplet","region":"nyc3","size":"s-1vcpu-1gb","image":"ubuntu-20-04-x64"}' \
          -H "Authorization: Bearer dop_v1_ebdc6f0bc1baf78d18d6dd607033ee330c9f3de8c4ecb0f4367b5b12fab5b04a" \
          -H "Content-Type: application/json"

trigger:
  event:
    - push
    - pull_request
  branch:
    - main
