---
kind: pipeline
type: digitalocean
name: deploy_droplet

token:
  from_secret: token
steps:
- name: greeting
  commands:
  - echo hello world
trigger:
  event:
    - push
    - pull_request
  branch:
    - main