---
kind: pipeline
type: digitalocean
name: default

token:
  from_secret: token
steps:
- name: greeting
  commands:
  - echo hello world!! This is rohit
trigger:
  event:
    - push
    - pull_request
  branch:
    - main