kind: pipeline
name: default

steps:
  - name: deploy_droplet
    image: curlimages/curl:latest
    environment:
      DO_TOKEN:
        from_secret: do_token  # Use the secret for the token
    commands:
      - |
        curl -X POST "https://api.digitalocean.com/v2/droplets" \
          -d '{"name":"My-Droplet","region":"nyc3","size":"s-1vcpu-1gb","image":"ubuntu-20-04-x64"}' \
          -H "Authorization: Bearer dop_v1_0122e7541e1172350ea0be69dafc340c0811ff8ec98ccd2f44e4a4cb782591c4" \
          -H "Content-Type: application/json"

trigger:
  event:
    - push
    - pull_request
  branch:
    - main
