kind: pipeline
name: default

steps:
  - name: deploy_droplet
    image: python:3.8
    commands:
      - pip install requests
      - pip install json
      - python digitalocean.py

trigger:
  event:
    - push
    - pull_request
  branch:
    - main
