---
kind: pipeline
name: deploy_droplet
steps:
  - name: install_dependencies
    image: python:3.8
    commands:
      - python --version
  - name: deploy_droplet
    image: curlimages/curl
    commands:
      - >
        curl -X POST \
<<<<<<< HEAD
         -H "Content-Type: application/json" \
         -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
         -d '{"name":"example.com","region":"nyc3","size":"s-1vcpu-1gb","image":"ubuntu-20-04-x64","ssh_keys":[289794,"3b:16:e4:bf:8b:00:8b:b8:59:8c:a9:d3:f0:19:fa:45"],"backups":true,"ipv6":true,"monitoring":true,"tags":["env:prod","web"],"user_data":"#cloud-config\nruncmd:\n  - touch /test.txt\n","vpc_uuid":"760e09ef-dc84-11e8-981e-3cfdfeaae000"}' \
=======
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer dop_v1_019baae72b0cd0329f43af80747079b5776aa9cdf89a59e643a31df045c54b77" \
          -d '{
            "name": "example.com",
            "region": "nyc3",
            "size": "s-1vcpu-1gb",
            "image": "ubuntu-20-04-x64",
            "ssh_keys": [289794,"3b:16:e4:bf:8b:00:8b:b8:59:8c:a9:d3:f0:19:fa:45"],
            "backups": true,
            "ipv6": true,
            "monitoring": true,
            "tags": ["env:prod", "web"],
            "user_data": "#cloud-config\nruncmd:\n  - touch /test.txt\n",
            "vpc_uuid": "760e09ef-dc84-11e8-981e-3cfdfeaae000"
          }' \
>>>>>>> d076daf77d1d8d97abbe50679c30b7e702a93d65
          "https://api.digitalocean.com/v2/droplets"
trigger:
  event:
    - push
    - pull_request
  branch:
    - main